# Generated by Django 3.0.5 on 2020-05-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
